# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-10 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u673a\u623f\u540d\u79f0')),
                ('address', models.CharField(max_length=128, unique=True, verbose_name='\u5730\u5740')),
                ('contact', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u673a\u623f',
                'verbose_name_plural': '\u673a\u623f',
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7f51\u5361\u540d')),
                ('macaddr', models.CharField(max_length=128, unique=True, verbose_name='MAC\u5730\u5740')),
                ('ipaddr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP\u5730\u5740')),
                ('netmask', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u5b50\u7f51\u63a9\u7801')),
                ('memo', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '\u7f51\u5361',
                'verbose_name_plural': '\u7f51\u5361',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u59d3\u540d')),
                ('department', models.CharField(max_length=32, verbose_name='\u90e8\u95e8')),
                ('tel', models.BigIntegerField(verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('qq', models.BigIntegerField(verbose_name='QQ\u53f7')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1\u5730\u5740')),
            ],
            options={
                'verbose_name': '\u4eba\u5458\u4fe1\u606f',
                'verbose_name_plural': '\u4eba\u5458\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, verbose_name='\u5185\u5b58\u578b\u53f7')),
                ('slot', models.CharField(max_length=64, verbose_name='\u63d2\u69fd')),
                ('capacity', models.IntegerField(verbose_name='\u5185\u5b58\u5927\u5c0f\uff08MB\uff09')),
                ('manufacturer', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u751f\u4ea7\u5382\u5546')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('update_data', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'RAM',
                'verbose_name_plural': 'RAM',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='UUID')),
                ('hostname', models.CharField(max_length=64, verbose_name='\u4e3b\u673a\u540d')),
                ('relaynum', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u4e2d\u7ee7\u53f7')),
                ('cpuinfo', models.CharField(blank=True, max_length=64, null=True)),
                ('meminfo', models.CharField(blank=True, max_length=64, null=True)),
                ('dns', models.CharField(blank=True, max_length=64, null=True, verbose_name='DNS')),
                ('os_type', models.CharField(max_length=64, null=True, verbose_name='\u7cfb\u7edf\u7c7b\u578b')),
                ('os_version', models.CharField(max_length=64, null=True, verbose_name='\u7cfb\u7edf\u7248\u672c')),
                ('os_kernel', models.CharField(max_length=64, null=True, verbose_name='\u7cfb\u7edf\u5185\u6838')),
                ('status', models.SmallIntegerField(choices=[(0, '\u5728\u7ebf'), (1, '\u4e0b\u7ebf'), (2, '\u672a\u77e5'), (3, '\u6545\u969c'), (4, '\u5907\u7528')], default=0)),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mc.PersonalInfo', verbose_name='\u8d1f\u8d23\u4eba')),
                ('idc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mc.IDC', verbose_name='IDC\u673a\u623f')),
            ],
            options={
                'verbose_name': '\u62e8\u53f7\u5668',
                'verbose_name_plural': '\u62e8\u53f7\u5668',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Tag name')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mc.PersonalInfo')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mc.Tag'),
        ),
        migrations.AddField(
            model_name='ram',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mc.Schedule', verbose_name='\u4e3b\u673a'),
        ),
        migrations.AddField(
            model_name='nic',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mc.Schedule', verbose_name='\u4e3b\u673a'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('uuid', 'hostname')]),
        ),
        migrations.AlterUniqueTogether(
            name='ram',
            unique_together=set([('host', 'slot')]),
        ),
        migrations.AlterUniqueTogether(
            name='nic',
            unique_together=set([('host', 'name')]),
        ),
    ]
