# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-12 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ram',
            old_name='create_data',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='update_data',
            new_name='update_date',
        ),
        migrations.AlterField(
            model_name='nic',
            name='ipaddr',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='IP\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='cpuinfo',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='meminfo',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f'),
        ),
    ]
