# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-14 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mc', '0002_auto_20170412_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='uuid',
            new_name='sn',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('sn', 'hostname')]),
        ),
    ]
