# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-17 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc', '0003_auto_20170414_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='meminfo',
            new_name='mem_size',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sn',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='SN'),
        ),
    ]
