# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-19 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mc', '0005_auto_20170417_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_model', models.CharField(blank=True, max_length=128, verbose_name='CPU\u578b\u53f7')),
                ('cpu_count', models.SmallIntegerField(verbose_name='\u7269\u7406CPU\u4e2a\u6570')),
                ('cpu_core', models.SmallIntegerField(verbose_name='CPU\u6838\u6570')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('update_data', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CPU\u90e8\u4ef6',
                'verbose_name_plural': 'CPU\u90e8\u4ef6',
            },
        ),
        migrations.RenameField(
            model_name='idc',
            old_name='name',
            new_name='idc_name',
        ),
        migrations.RenameField(
            model_name='nic',
            old_name='host',
            new_name='hostname',
        ),
        migrations.RenameField(
            model_name='nic',
            old_name='name',
            new_name='nic_name',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='host',
            new_name='hostname',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='mem_size',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f(MB)'),
        ),
        migrations.AlterUniqueTogether(
            name='nic',
            unique_together=set([('hostname', 'nic_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='ram',
            unique_together=set([('hostname', 'slot')]),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='cpu',
            name='hostname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mc.Schedule', verbose_name='\u4e3b\u673a'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='cpuinfo',
        ),
    ]
