# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-19 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc', '0007_auto_20170419_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='dns',
            field=models.CharField(blank=True, max_length=64, verbose_name='DNS'),
        ),
    ]
