# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-19 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc', '0008_auto_20170419_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='os_release',
            field=models.CharField(max_length=64, verbose_name='\u7cfb\u7edf\u5185\u6838'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='os_type',
            field=models.CharField(max_length=64, verbose_name='\u7cfb\u7edf\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='os_version',
            field=models.CharField(max_length=64, verbose_name='\u7cfb\u7edf\u7248\u672c'),
        ),
    ]
