# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-19 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc', '0009_auto_20170419_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='sn',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hostname',
            field=models.CharField(max_length=64, unique=True, verbose_name='\u4e3b\u673a\u540d'),
        ),
    ]
